version: '3.4'
#Network
networks:
  demoMicroServices:

services:
  #DB
  customerdb:
   container_name: customer-db
   image: mcr.microsoft.com/mssql/server:2022-latest
   environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=Azerty123+
   networks:
    - demoMicroServices
   ports:
    - 1433:1433
  ##
  authapi:
    container_name: auth-api
    build:
      context: .
      dockerfile: AuthAPI/Dockerfile
    image: ${DOCKER_REGISTRY-}authapi
    networks:
      demoMicroServices:
  #
  minimalapi:
    container_name: minimal-api
    build:
      context: .
      dockerfile: MinimalAPI/Dockerfile
    image: ${DOCKER_REGISTRY-}minimalapi
    networks:
      demoMicroServices:
    environment:
     - DB_HOST= customerdb
     - DB_NAME= dms_customer
     - DB_SA_PASSWORD= abc123
  # API Gateway
  apigateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: APIGateway/Dockerfile
    image: ${DOCKER_REGISTRY-}apigateway
    ports:
      - "8001:80"
    #environment:
    #  - AUTH_API_URL=http://authapi:5000
    #depends_on:
    #  - authapi
    networks:
      demoMicroServices: